### ISSUE TITLE
Training in new languages

### ISSUE THREAD

**Issue by helloworld-steinheil** [Niger-Volta-LTI/yoruba-adr#23]
I want training in difference language, What part I have to modify like data, tokenizer, vocabulary set ...  ???
Thank you for your response.

**Comment by ruohoruotsi** [comment]
Hi there, sorry for the terrible long delay in responding. :( 
To train a new language, you mostly have to prepare new texts. The tokenizer if its a Latin characterset should be okay, but if it's another you may have to modify the tokenizer, which operates mainly on white-space, however any tokenizer supported by `ntlk` will be a minimal change.   The vocabulary is derived from the training text, so that should be fine.

Apologies again for the tardy response. And if you have a language specific question, please feel free to add it here or make a new issue.
