### ISSUE TITLE
Module nltk not found

### ISSUE THREAD

**Issue by emmadenagbe** [Niger-Volta-LTI/yoruba-adr#9]
Can u help with this,am using python3 and whenever i run the .sh script on terminal ,this error shoot out module nltk not found and i have install nltk

**Comment by nvlong198** [comment]
Hi @ruohoruotsi @emmadedayo 
I wonder whether what **Size** mean? Is it Layer and rnn_size ?
![image](https://user-images.githubusercontent.com/23328191/53745323-6976ef80-3ed1-11e9-9a0b-7820ef382a6a.png)

**Comment by emmadedayo** [comment]
I don't get,wat do u mean

**Comment by ruohoruotsi** [comment]
Hello @emmadedayo, for NLTK please refer to the [README](https://github.com/Niger-Volta-LTI/yoruba-adr/blob/master/README.md).  Please note that NLTK will need some extra efforts if you've installed it for the first time.

you will need to run python3 from your terminal and do:
```
 >>> import nltk
 >>> nltk.download('punkt')
```
This will download the necessary NLTK parts ... otherwise you'll have the error below

>  Resource punkt not found.
>  Please use the NLTK Downloader to obtain the resource:

Let me know if that helps.

**Comment by ruohoruotsi** [comment]
@emmadedayo If it will be helpful, I can upload a video that shows the steps in closer detail. Let me know how you get one with the setup. Cheers.

**Comment by emmadenagbe** [comment]
okay @ruohoruotsi, have done it but still showing error
![screenshot from 2019-03-07 17-34-42](https://user-images.githubusercontent.com/18017643/53972598-65301980-40ff-11e9-84dd-1a51424099b2.png)

**Comment by ruohoruotsi** [comment]
@emmadedayo this error is not related to NLTK. The error says to "Please check the path of your train src and tgt files". Since the NLTK issue is resolved I will close this issue. 

Regarding the most recent error: I will upload a video that shows the expected output starting from cloning the repo and running the build script.

**Comment by emmadenagbe** [comment]
Okay @ruohoruotsi,pls upload video

**Comment by ruohoruotsi** [comment]
@emmadedayo 
(1) Please study the video https://www.youtube.com/watch?v=Lh7XFc7S_8Y, as I clone 2 repos (having already installed dependencies & NLTK) to get the newest code
(2) then I run the training script. 

It is important to check the first errors you encounter, for example above in your error-output, your data preprocessing step is failing. You have to debug why. If you follow the steps on a clean system, tested on Linux/Ubuntu & MacOS, you shouldn't meet any problems.  Let me know how you get on, and we'll work to resolve all issues.

**Comment by ruohoruotsi** [comment]
@emmadedayo I have added a Quickstart using a pre-trained model (so you don't have to train your own model). Please try this short Jupyter notebook and see if it can help out. Cheers 

https://github.com/Niger-Volta-LTI/yoruba-adr/blob/master/correct_yoruba_diacritics.ipynb
